"""
The Syracuse (also called Collatz or Hailstone) sequence is generated by starting with a natural number and repeatedly 
applying the following function until reaching 1:
 syr(x) = 1/2 if x is even; and 
syr(x) = 3x + 1 if x is odd 
For example, the Syracuse sequence starting with 5 is: 5, 16, 8, 4, 2, 1. 
Use of inbuilt function or math library is not allowed.
This sequence will always go to 1 for every possible starting value.
Write a program that 
1.	Gets a starting value from the user 
2.	Prints the Syracuse sequence for that starting value.

"""
def syr(x: int) -> list:
    if x == 1:
        return [x]
    else:
        if x % 2 == 0:
            return [x] + syr(x // 2)
        else:
            return [x] + syr(3 * x + 1)
        
x = int(input("Enter a number: "))
print(syr(x))